
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2010-31-01
Description: 'Cloud Resume Challenge Backend Infrastructure with Function URL'

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    Environment:
      Variables:
        TABLE_NAME: !Ref VisitorCountTable

Resources:
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitor-count
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  VisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: visitor-count-function
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCountTable
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowCredentials: false
          AllowHeaders:
            - "Content-Type"
            - "X-Amz-Date"
            - "Authorization"
            - "X-Api-Key"
            - "X-Amz-Security-Token"
          AllowMethods:
            - "GET"
            - "OPTIONS"
          AllowOrigins:
            - "*"
          MaxAge: 86400

Outputs:
  VisitorCountFunctionUrl:
    Description: "Lambda Function URL for visitor count"
    Value: !GetAtt VisitorCountFunctionUrl.FunctionUrl
    Export:
      Name: VisitorCountFunctionUrl
  
  VisitorCountFunction:
    Description: "Visitor Count Lambda Function ARN"
    Value: !GetAtt VisitorCountFunction.Arn
    Export:
      Name: VisitorCountFunctionArn
  
  VisitorCountTable:
    Description: "DynamoDB table name"
    Value: !Ref VisitorCountTable
    Export:
      Name: VisitorCountTableName

